global_costmap:
  #代价地图的世界坐标系
  global_frame: map
  #机器人底座的局部坐标系
  robot_base_frame: base_link
  #代价地图的更新频率
  update_frequency: 2.5
  #代价地图的发布频率
  publish_frequency: 3.0

  # cost_scaling_factor: 5 #36
  # inflation_radius: 0.18
  #决定代价地图是否需要根据map_server提供的地图信息进行初始化，如果不需要使用已有的地图或者map_server，最好将该参数设置为false
  static_map: true



